name: spin_foot_lucky_star
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  in_app_purchase: ^3.1.13
  provider: ^6.1.5+1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  vibration: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  device_preview: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/wheel_outside.png
    - assets/wheel_inside.png
    - assets/wheel_top.png
    - assets/wheel_example.png
    - assets/ball_static.png
    - assets/ball_dynamic_1.png
    - assets/ball_dynamic_2.png
    - assets/ball_dynamic_3.png
    - assets/balance.png
    - assets/coin.png
    - assets/shop.png
    - assets/withdraw.png
    - assets/wheel.png
    - assets/settings.png
    - assets/button.png
    - assets/background.png
    - assets/logo.png
    - assets/splash_logo.png
    - assets/bet_card_bg.png
    - assets/autoplay_button.png
    - assets/counter_button.png
    - assets/counter_bg.png
    - assets/start_button.png
    - assets/cash_out_button.png
    - assets/bet_button.png
    - assets/bet_x2_bg.png
    - assets/bet_x2_label.png
    - assets/bet_x2_switch_bg.png
    - assets/bet_x2_switch_pin.png
    - assets/bet_example.png
